/**
 * Cached read helpers for the public directory routes.
 *
 * Each helper:
 *   - reads from Drizzle (which connects via the Supabase pooler service URI
 *     and therefore bypasses RLS — these are public read paths anyway)
 *   - is wrapped in `unstable_cache` with deterministic key parts and the
 *     same revalidation tags the Payload `afterChange` hooks fire from
 *     `apps/web/collections/{Businesses,Coupons}.ts`
 *   - lives behind a 1-hour ISR baseline (`revalidate: 3600`); merchant edits
 *     in `/admin` punch through that baseline via `revalidateTag(...)`
 *
 * Tag names are generated by `@localchamp/logic/cache-tags`. The read side
 * (this file) and the write side (collections) MUST go through those helpers
 * so they can never disagree on a tag name.
 *
 * Numeric column quirk: postgres-js returns `numeric` columns as strings to
 * preserve arbitrary precision. We convert to JS `number` at this boundary
 * so route components can assume number types throughout.
 *
 * Drizzle helpers (`and`, `eq`, `sql`, etc.) come from `@localchamp/db` rather
 * than `drizzle-orm` directly — that package re-exports the helpers so apps/web
 * doesn't need a direct `drizzle-orm` dependency. Keeps the ORM choice owned
 * by the db package.
 */

import { unstable_cache } from 'next/cache';
import { and, asc, db, desc, eq, schema, sql } from '@localchamp/db';
import {
  businessSlugTag,
  businessTag,
  categoryTag,
  cityTag,
  directoryTag,
  titleizeSlug,
} from '@localchamp/logic';

// `schema` is the namespace re-export from @localchamp/db. Aliasing the
// individual tables here keeps the rest of the file idiomatic.
const { businesses, cities, coupons, sourcing } = schema;

// =====================================================================
// Returned shapes (consumed by route components)
// =====================================================================

export type CityRow = {
  slug: string;
  displayName: string;
  state: string;
  region: string | null;
  heroImageUrl: string | null;
  featured: boolean;
  sortOrder: number;
};

export type CategorySummary = {
  /** category_slug (also the URL segment) */
  slug: string;
  /** human-friendly display name (e.g. "Pet Supplies" for `pet-supplies`) */
  displayName: string;
  /** count of businesses in this city + category */
  businessCount: number;
};

export type DirectoryBusinessRow = {
  id: string;
  name: string;
  slug: string;
  citySlug: string;
  categorySlug: string;
  status: string;
  starRating: number | null;
  reviewCount: number;
  cpsScore: number;
  localLoopScore: number;
  phone: string | null;
  addressStreet: string | null;
  addressCity: string | null;
  addressState: string | null;
  addressPostalCode: string | null;
};

export type BusinessDetail = DirectoryBusinessRow & {
  /** Decoded from PostGIS `geometry(Point, 4326)`; null if unset or unparseable. */
  geo: { latitude: number; longitude: number } | null;
};

export type CouponRow = {
  id: string;
  title: string;
  description: string | null;
  discountValue: string;
  terms: string | null;
  isActive: boolean;
};

export type SourcingPartner = {
  /** sourcing edge id */
  id: string;
  /** the OTHER business on the edge (not the one we queried for) */
  partnerId: string;
  partnerName: string;
  partnerSlug: string;
  partnerCitySlug: string;
  partnerCategorySlug: string;
  /** 'sells_to' = current business sells to partner; 'buys_from' = current buys from partner. */
  direction: 'sells_to' | 'buys_from';
};

// =====================================================================
// Pure helpers (in-process; not cached)
// =====================================================================

function toNumberOrNull(value: string | number | null | undefined): number | null {
  if (value === null || value === undefined) return null;
  const parsed = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function toNumberOrZero(value: string | number | null | undefined): number {
  return toNumberOrNull(value) ?? 0;
}

/**
 * Decode a `ST_AsGeoJSON(geometry)` string into `{ latitude, longitude }`.
 * GeoJSON Point coordinates are `[longitude, latitude]` — we swap to the
 * `lat, lng` ordering Schema.org `GeoCoordinates` expects.
 */
function decodePostgisPoint(
  geoJson: string | null,
): { latitude: number; longitude: number } | null {
  if (!geoJson) return null;
  try {
    const parsed = JSON.parse(geoJson) as {
      type?: string;
      coordinates?: unknown;
    };
    if (
      parsed.type !== 'Point' ||
      !Array.isArray(parsed.coordinates) ||
      parsed.coordinates.length !== 2
    ) {
      return null;
    }
    const [lng, lat] = parsed.coordinates as [unknown, unknown];
    if (typeof lng !== 'number' || typeof lat !== 'number') return null;
    return { latitude: lat, longitude: lng };
  } catch {
    return null;
  }
}

const businessSelect = {
  id: businesses.id,
  name: businesses.name,
  slug: businesses.slug,
  citySlug: businesses.citySlug,
  categorySlug: businesses.categorySlug,
  status: businesses.status,
  starRating: businesses.starRating,
  reviewCount: businesses.reviewCount,
  cpsScore: businesses.cpsScore,
  localLoopScore: businesses.localLoopScore,
  phone: businesses.phone,
  addressStreet: businesses.addressStreet,
  addressCity: businesses.addressCity,
  addressState: businesses.addressState,
  addressPostalCode: businesses.addressPostalCode,
} as const;

type RawBusinessRow = {
  id: string;
  name: string;
  slug: string;
  citySlug: string;
  categorySlug: string;
  status: string;
  starRating: string | null;
  reviewCount: string | null;
  cpsScore: string | null;
  localLoopScore: string | null;
  phone: string | null;
  addressStreet: string | null;
  addressCity: string | null;
  addressState: string | null;
  addressPostalCode: string | null;
};

function shapeBusinessRow(row: RawBusinessRow): DirectoryBusinessRow {
  return {
    id: row.id,
    name: row.name,
    slug: row.slug,
    citySlug: row.citySlug,
    categorySlug: row.categorySlug,
    status: row.status,
    starRating: toNumberOrNull(row.starRating),
    reviewCount: toNumberOrZero(row.reviewCount),
    cpsScore: toNumberOrZero(row.cpsScore),
    localLoopScore: toNumberOrZero(row.localLoopScore),
    phone: row.phone,
    addressStreet: row.addressStreet,
    addressCity: row.addressCity,
    addressState: row.addressState,
    addressPostalCode: row.addressPostalCode,
  };
}

// =====================================================================
// Cached fetchers
// =====================================================================

/**
 * All cities, featured-first, then by sort_order, then alpha.
 *
 * Wrapped in an async function (rather than a top-level `unstable_cache`
 * binding) so this fetcher follows the same pattern as the parameterized
 * fetchers below — uniform style, easier to add params later.
 */
export async function getCities(): Promise<CityRow[]> {
  return unstable_cache(
    async (): Promise<CityRow[]> => {
      const rows = await db
        .select({
          slug: cities.slug,
          displayName: cities.displayName,
          state: cities.state,
          region: cities.region,
          heroImageUrl: cities.heroImageUrl,
          featured: cities.featured,
          sortOrder: cities.sortOrder,
        })
        .from(cities)
        .orderBy(desc(cities.featured), asc(cities.sortOrder), asc(cities.displayName));
      return rows;
    },
    ['directory', 'getCities'],
    { tags: [directoryTag()], revalidate: 3600 },
  )();
}

/** Single city by slug; null if not found. */
export async function getCityBySlug(slug: string): Promise<CityRow | null> {
  return unstable_cache(
    async (): Promise<CityRow | null> => {
      const [row] = await db
        .select({
          slug: cities.slug,
          displayName: cities.displayName,
          state: cities.state,
          region: cities.region,
          heroImageUrl: cities.heroImageUrl,
          featured: cities.featured,
          sortOrder: cities.sortOrder,
        })
        .from(cities)
        .where(eq(cities.slug, slug))
        .limit(1);
      return row ?? null;
    },
    ['directory', 'getCityBySlug', slug],
    { tags: [directoryTag(), cityTag(slug)], revalidate: 3600 },
  )();
}

/**
 * Distinct `category_slug`s present in this city, with a count of businesses
 * per category and a human-friendly display name (e.g. `pet-supplies` →
 * "Pet Supplies"). Drives the city landing page's "Browse by category" grid.
 */
export async function getCategoriesForCity(citySlug: string): Promise<CategorySummary[]> {
  return unstable_cache(
    async (): Promise<CategorySummary[]> => {
      const rows = await db
        .select({
          slug: businesses.categorySlug,
          businessCount: sql<number>`count(*)::int`,
        })
        .from(businesses)
        .where(eq(businesses.citySlug, citySlug))
        .groupBy(businesses.categorySlug)
        .orderBy(asc(businesses.categorySlug));
      return rows.map((r) => ({
        slug: r.slug,
        displayName: titleizeSlug(r.slug),
        businessCount: Number(r.businessCount),
      }));
    },
    ['directory', 'getCategoriesForCity', citySlug],
    { tags: [directoryTag(), cityTag(citySlug)], revalidate: 3600 },
  )();
}

/** Top featured businesses for a city, ranked by CPS then star rating. */
export async function getFeaturedBusinesses(
  citySlug: string,
  limit = 6,
): Promise<DirectoryBusinessRow[]> {
  return unstable_cache(
    async (): Promise<DirectoryBusinessRow[]> => {
      const rows = await db
        .select(businessSelect)
        .from(businesses)
        .where(eq(businesses.citySlug, citySlug))
        .orderBy(desc(businesses.cpsScore), desc(businesses.starRating), asc(businesses.name))
        .limit(limit);
      return rows.map(shapeBusinessRow);
    },
    ['directory', 'getFeaturedBusinesses', citySlug, String(limit)],
    { tags: [directoryTag(), cityTag(citySlug)], revalidate: 3600 },
  )();
}

/** All businesses in a city + category, ranked for the listing page. */
export async function getBusinessesByCategory(
  citySlug: string,
  categorySlug: string,
): Promise<DirectoryBusinessRow[]> {
  return unstable_cache(
    async (): Promise<DirectoryBusinessRow[]> => {
      const rows = await db
        .select(businessSelect)
        .from(businesses)
        .where(
          and(
            eq(businesses.citySlug, citySlug),
            eq(businesses.categorySlug, categorySlug),
          ),
        )
        .orderBy(desc(businesses.cpsScore), desc(businesses.starRating), asc(businesses.name));
      return rows.map(shapeBusinessRow);
    },
    ['directory', 'getBusinessesByCategory', citySlug, categorySlug],
    {
      tags: [directoryTag(), cityTag(citySlug), categoryTag(citySlug, categorySlug)],
      revalidate: 3600,
    },
  )();
}

/**
 * Single business by slug, validated against city + category. Returning null
 * when the path doesn't match the row's actual city/category prevents URL
 * fuzzing where `/boulder/coffee/asheville-business` could surface the
 * Asheville business under a Boulder URL.
 *
 * Includes decoded geo coordinates for JSON-LD `LocalBusiness.geo`. We
 * select `ST_AsGeoJSON(location)` via raw SQL because `businesses.location`
 * is intentionally excluded from the Drizzle introspection (Payload owns
 * the writes via `@payloadcms/drizzle`'s `geometryColumn` helper).
 */
export async function getBusinessBySlug(
  citySlug: string,
  categorySlug: string,
  businessSlug: string,
): Promise<BusinessDetail | null> {
  return unstable_cache(
    async (): Promise<BusinessDetail | null> => {
      const [row] = await db
        .select({
          ...businessSelect,
          geoJson: sql<string | null>`ST_AsGeoJSON("location")::text`,
        })
        .from(businesses)
        .where(eq(businesses.slug, businessSlug))
        .limit(1);

      if (!row) return null;

      // Defense-in-depth: only return the row when the URL's city + category
      // match what the database has. Mismatches indicate URL fuzzing.
      if (row.citySlug !== citySlug || row.categorySlug !== categorySlug) {
        return null;
      }

      return {
        ...shapeBusinessRow(row),
        geo: decodePostgisPoint(row.geoJson),
      };
    },
    // Cache key MUST include citySlug + categorySlug, not just businessSlug.
    // The function returns null for URL/row mismatches (defense-in-depth above);
    // without those segments in the key, two distinct URLs like
    // `/boulder/coffee/asheville-books-and-bindery` (mismatch → null) and
    // `/asheville/bookstore/asheville-books-and-bindery` (the canonical URL)
    // would collide on the same key and the second request would return the
    // cached null. Tags still target city/category for granular invalidation.
    ['directory', 'getBusinessBySlug', citySlug, categorySlug, businessSlug],
    {
      tags: [
        directoryTag(),
        cityTag(citySlug),
        categoryTag(citySlug, categorySlug),
        businessSlugTag(businessSlug),
      ],
      revalidate: 3600,
    },
  )();
}

/** Active coupons attached to a business, newest first. */
export async function getCouponsForBusiness(businessId: string): Promise<CouponRow[]> {
  return unstable_cache(
    async (): Promise<CouponRow[]> => {
      const rows = await db
        .select({
          id: coupons.id,
          title: coupons.title,
          description: coupons.description,
          discountValue: coupons.discountValue,
          terms: coupons.terms,
          isActive: coupons.isActive,
        })
        .from(coupons)
        .where(and(eq(coupons.businessId, businessId), eq(coupons.isActive, true)))
        .orderBy(desc(coupons.createdAt));
      return rows.map((r) => ({
        id: r.id,
        title: r.title,
        description: r.description,
        discountValue: r.discountValue,
        terms: r.terms,
        isActive: r.isActive ?? true,
      }));
    },
    ['directory', 'getCouponsForBusiness', businessId],
    { tags: [directoryTag(), businessTag(businessId)], revalidate: 3600 },
  )();
}

/**
 * Verified Local Loop sourcing edges where the given business is either the
 * buyer or the seller. Returns the partner business on the other end of each
 * edge, with direction context. Empty at MVP launch — surfaces as an empty
 * state on the business detail page.
 */
export async function getSourcingForBusiness(businessId: string): Promise<SourcingPartner[]> {
  return unstable_cache(
    async (): Promise<SourcingPartner[]> => {
      // Two queries (buys_from + sells_to), each joined to the partner business
      // row. Cleaner than a single self-join with a CASE expression.
      const buysFrom = await db
        .select({
          id: sourcing.id,
          partnerId: businesses.id,
          partnerName: businesses.name,
          partnerSlug: businesses.slug,
          partnerCitySlug: businesses.citySlug,
          partnerCategorySlug: businesses.categorySlug,
        })
        .from(sourcing)
        .innerJoin(businesses, eq(businesses.id, sourcing.sellerId))
        .where(and(eq(sourcing.buyerId, businessId), eq(sourcing.verified, true)));

      const sellsTo = await db
        .select({
          id: sourcing.id,
          partnerId: businesses.id,
          partnerName: businesses.name,
          partnerSlug: businesses.slug,
          partnerCitySlug: businesses.citySlug,
          partnerCategorySlug: businesses.categorySlug,
        })
        .from(sourcing)
        .innerJoin(businesses, eq(businesses.id, sourcing.buyerId))
        .where(and(eq(sourcing.sellerId, businessId), eq(sourcing.verified, true)));

      return [
        ...buysFrom.map((r) => ({ ...r, direction: 'buys_from' as const })),
        ...sellsTo.map((r) => ({ ...r, direction: 'sells_to' as const })),
      ];
    },
    ['directory', 'getSourcingForBusiness', businessId],
    { tags: [directoryTag(), businessTag(businessId)], revalidate: 3600 },
  )();
}

/**
 * Slugs to prebuild for `/[city_slug]/[category_slug]/[business_slug]`.
 * Returns the top 100 by CPS (with star rating tiebreak); the business
 * detail page sets `dynamicParams = true` so anything outside this set is
 * still rendered on demand.
 */
export async function getStaticBusinessParams(): Promise<
  Array<{ city_slug: string; category_slug: string; business_slug: string }>
> {
  return unstable_cache(
    async () => {
      const rows = await db
        .select({
          slug: businesses.slug,
          citySlug: businesses.citySlug,
          categorySlug: businesses.categorySlug,
        })
        .from(businesses)
        .orderBy(desc(businesses.cpsScore), desc(businesses.starRating))
        .limit(100);
      return rows.map((r) => ({
        city_slug: r.citySlug,
        category_slug: r.categorySlug,
        business_slug: r.slug,
      }));
    },
    ['directory', 'getStaticBusinessParams'],
    { tags: [directoryTag()], revalidate: 3600 },
  )();
}
